server {
    listen 5173;

    location /env-config.js {
        add_header Content-Type application/javascript;
        return 200 "window.__ENV__ = { VITE_ORCHESTRATOR_URL: '$VITE_ORCHESTRATOR_URL', VITE_YJS_URL: '$VITE_YJS_URL' };";
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
